### ISSUE TITLE
Bump truffle hdwallet-provider to 1.4.0

### ISSUE THREAD

**Issue by tavakyan** [maticnetwork/contracts#365]
I'm having issues with deploying the child contracts.  

The chain I'm deploying to is local and I have the chain id correct so the only solution seems to suggest a bump of the hdwallet-provider version: https://github.com/trufflesuite/truffle/issues/4147

Also I noticed in the dependencies you guys use a deprecated package: https://www.npmjs.com/package/truffle-hdwallet-provider

This should likely be removed and replaced with @truffle/hdwallet-provider@1.4.0

**Comment by tavakyan** [comment]
This happens also when I use the matic-cli tool with devnet

`Starting migrations...
======================
> Network name:    'bor'
> Network id:      15001
> Block gas limit: 0x7a1200


5_deploy_child_contracts.js
===========================

   Deploying 'SafeMath'
   --------------------
Error: Error:  *** Deployment Failed ***

"SafeMath" -- only replay-protected (EIP-155) transactions allowed over RPC.

    at Migration._deploy (/Users/tavakayn/Projects/telcoin/telcoin/docker/polygon/code/contracts/node_modules/truffle/build/webpack:/packages/truffle-migrate/migration.js:124:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration._load (/Users/tavakayn/Projects/telcoin/telcoin/docker/polygon/code/contracts/node_modules/truffle/build/webpack:/packages/truffle-migrate/migration.js:54:1)
    at Migration.run (/Users/tavakayn/Projects/telcoin/telcoin/docker/polygon/code/contracts/node_modules/truffle/build/webpack:/packages/truffle-migrate/migration.js:160:1)
Truffle v5.0.34 (core: 5.0.34)
Node v16.2.0`
